# Generated by Django 5.2.1 on 2025-06-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_language',
        ),
    ]
