# Generated by Django 5.2.1 on 2025-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_id', models.CharField(max_length=100, unique=True)),
                ('enable_media', models.BooleanField(default=False)),
                ('theme_class', models.CharField(default='default-theme', max_length=50)),
                ('naru_region_code', models.CharField(max_length=20)),
            ],
        ),
    ]
